version: '3.9'
services:
  books_api:
    container_name: books_api_service
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "${BOOKS_API_PORT}:${BOOKS_API_PORT}"
    depends_on:
      - database

  database:
    container_name: primary_db_service
    image: postgres:13
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
        - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_service
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
    pgadmin:
    db:
    init.sql:

