export const APP_PREFIX = 'api/v1';
export const SWAGGER_API_ROOT = 'api/v1/docs';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const AUTH_REPOSITORY = 'AUTH_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const BOOKS_REPOSITORY = 'BOOKS_REPOSITORY';
export const LEND_REPOSITORY = 'LEND_REPOSITORY';

export const AUTH_SERVICE = 'AUTH_SERVICE';
export const USER_SERVICE = 'USER_SERVICE';
export const BOOKS_SERVICE = 'BOOKS_SERVICE';
