export const SWAGGER_API_ROOT = 'api/v1/docs';
export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLES_REPOSITORY = 'ROLES_REPOSITORY';
export const BOOKS_REPOSITORY = 'BOOKS_REPOSITORY';
export const LENDS_REPOSITORY = 'LENDS_REPOSITORY';
